[package]
name = "test-ai"
version = "0.1.0"
authors = ["user <ume.drink@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.codevs_reborn_lib]
path = "../codevs-reborn-lib"

[dev-dependencies]
rayon = "1.0"
