[package]
name = "test-ai"
version = "0.1.0"
authors = ["user <ume.drink@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_core = "0.37.0"
rusoto_lambda = "0.37.0"
rusoto_sqs = "0.37.0"
rusoto_s3 = "0.37.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.codevs_reborn_lib]
path = "../codevs-reborn-lib"
