[package]
name = "test-ai"
version = "0.1.0"
authors = ["user <ume.drink@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
log = "^0.4"
simple_logger = "^1"

[dependencies.codevs_reborn_lib]
path = "../codevs-reborn-lib"
